/// <reference lib="WebWorker" />

// Define the service worker type
declare const self: ServiceWorkerGlobalScope;

import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkOnly } from 'workbox-strategies';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

// Precache assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Install event - claim clients immediately
self.addEventListener('install', () => {
  self.skipWaiting(); 
});

// Claim clients immediately when activated
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

// Background sync plugin for notes
const bgSyncPlugin = new BackgroundSyncPlugin('NotesSyncQueue', {
  maxRetentionTime: 24 * 60, 
  onSync: async ({ queue }) => {
    let entry = await queue.shiftRequest();
    while (entry) {
      try {
        const noteData = await entry.request.clone().json();
        const response = await fetch(entry.request);
        
        if (!response.ok) {
          throw new Error('Sync failed');
        }
        
        console.log('Successfully synced note:', noteData.id);
      } catch (error) {
        console.error('Failed to sync note, re-queuing:', error);
        throw error;
      }
      entry = await queue.shiftRequest();
    }
  }
});

// Register route for note sync requests with background sync
registerRoute(
  ({ url, request }) => {
    return url.pathname.includes('/api/sync-note') && request.method === 'POST';
  },
  new NetworkOnly({
    plugins: [bgSyncPlugin]
  }),
  'POST'
);

// Listen for sync events from the main thread
self.addEventListener('sync', (event) => {
  if (event.tag === 'sync-notes') {
    event.waitUntil(doBackgroundSync());
  }
});

interface NoteData {
  id: string;
  syncStatus: string;
  lastSyncedAt?: string;
}

// Background sync function to process pending notes
async function doBackgroundSync() {
  try {
    const clients = await self.clients.matchAll({
      includeUncontrolled: true,
      type: 'window'
    });

    for (const client of clients) {
      client.postMessage({ type: 'GET_PENDING_NOTES' });
    }

    const databases = await indexedDB.databases();
    console.log('Available databases:', databases);

    for (const dbInfo of databases) {
      if (dbInfo.name && (dbInfo.name.includes('notes') || dbInfo.name.includes('db'))) {
        const dbReq = indexedDB.open(dbInfo.name, dbInfo.version);

        const idb = await new Promise<IDBDatabase>((resolve, reject) => {
          dbReq.onsuccess = () => resolve(dbReq.result);
          dbReq.onerror = () => reject(dbReq.error);
        });

        if (idb.objectStoreNames.contains('notes')) {
          const transaction = idb.transaction(['notes'], 'readonly');
          const objectStore = transaction.objectStore('notes');

          const getAllReq = objectStore.getAll();
          const allNotes = await new Promise<NoteData[]>((resolve, reject) => {
            getAllReq.onsuccess = () => resolve(getAllReq.result || []);
            getAllReq.onerror = () => reject(getAllReq.error);
          });

          const pendingNotes = allNotes.filter(note => note.syncStatus === 'pending');
          console.log(`Found ${pendingNotes.length} pending notes to sync`);

          for (const note of pendingNotes) {
            try {
              const response = await fetch('/api/sync-note', {
                method: 'POST',
                headers: {
                  'Content-Type': 'application/json',
                },
                body: JSON.stringify(note)
              });

              if (response.ok) {
                const updateTransaction = idb.transaction(['notes'], 'readwrite');
                const updateStore = updateTransaction.objectStore('notes');

                const getReq = updateStore.get(note.id);
                const noteToUpdate = await new Promise<NoteData>((resolve, reject) => {
                  getReq.onsuccess = () => resolve(getReq.result);
                  getReq.onerror = () => reject(getReq.error);
                });

                if (noteToUpdate) {
                  noteToUpdate.syncStatus = 'synced';
                  noteToUpdate.lastSyncedAt = new Date().toISOString();
                  updateStore.put(noteToUpdate);
                }
              }
            } catch (err) {
              console.error(`Error syncing note ${note.id}:`, err);
            }
          }
        }
      }
    }
  } catch (error) {
    console.error('Background sync failed:', error);
  }
}

// Listen for messages from the main thread
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SYNC_NOTES') {
    // @ts-expect-error - register is part of Background Sync API
    self.registration.sync.register('sync-notes');
  }

  if (event.data && event.data.type === 'PENDING_NOTES_RESPONSE') {
    const pendingNotes = event.data.pendingNotes as NoteData[];
    processPendingNotesFromMainThread(pendingNotes);
  }
});

async function processPendingNotesFromMainThread(pendingNotes: NoteData[]) {
  for (const note of pendingNotes) {
    try {
      const response = await fetch('/api/sync-note', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(note)
      });

      if (response.ok) {
        const clients = await self.clients.matchAll({
          includeUncontrolled: true,
          type: 'window'
        });

        for (const client of clients) {
          client.postMessage({
            type: 'UPDATE_NOTE_STATUS',
            noteId: note.id,
            status: 'synced',
            timestamp: new Date().toISOString()
          });
        }
      }
    } catch (err) {
      console.error(`Error syncing note ${note.id}:`, err);
    }
  }
}

// Define types for TypeScript
type IDBValidKey = string | number | Date | BufferSource | IDBValidKey[];

interface IDBDatabase {
  readonly name: string;
  readonly version: number;
  readonly objectStoreNames: DOMStringList;
  close(): void;
  createObjectStore(name: string, optionalParameters?: IDBObjectStoreParameters): IDBObjectStore;
  deleteObjectStore(name: string): void;
  transaction(storeNames: string | string[], mode?: IDBTransactionMode): IDBTransaction;
  addEventListener<K extends keyof ServiceWorkerGlobalScopeEventMap>(
    type: K,
    listener: (this: ServiceWorkerGlobalScope, ev: ServiceWorkerGlobalScopeEventMap[K]) => unknown,
    options?: boolean | AddEventListenerOptions
  ): void;
}

interface IDBObjectStore {
  readonly indexNames: DOMStringList;
  readonly keyPath: string | null;
  readonly name: string;
  readonly transaction: IDBTransaction;
  autoIncrement: boolean;
  add(value: unknown, key?: IDBValidKey): IDBRequest;
  clear(): IDBRequest;
  count(key?: IDBValidKey): IDBRequest<IDBCursorWithValue>;
  delete(key: IDBValidKey): IDBRequest;
  get(key: IDBValidKey): IDBRequest<unknown>;
  getAll(query?: IDBValidKey, count?: number): IDBRequest<unknown[]>;
  getAllKeys(query?: IDBValidKey, count?: number): IDBRequest<IDBValidKey[]>;
  getKey(key: IDBValidKey): IDBRequest<IDBValidKey>;
  index(name: string): IDBIndex;
  openCursor(range?: IDBValidKey, direction?: IDBCursorDirection): IDBRequest<IDBCursorWithValue>;
  openKeyCursor(range?: IDBValidKey, direction?: IDBCursorDirection): IDBRequest<IDBCursor>;
  put(value: unknown, key?: IDBValidKey): IDBRequest;
}